services:
  - type: web
    name: behere
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: NODE_ENV
        value: production
      - key: TAVILY_API_KEY
        sync: false
      - key: AI_BASE_URL
        sync: false
      - key: AI_API_KEY
        sync: false
      - key: AI_MODEL
        sync: false
